apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-test-app-v1
    version: v1
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test-app-v1
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: python-test-app-v1
        version: v1
    spec:
      containers:
          - image: eu.gcr.io/heu-green-testday/app:M9
            name: app
            envFrom:
              - configMapRef:
                  name: configmap-app
