apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: python-test-
nameSuffix: -v1

commonLabels:
  app: python-test-app-v1
  version: v1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: configmap-app
    behavior: create
    literals:
      - REDIS_HOST="redis"
      - REDIS_PORT="6379"
      - REDIS_DB="0"
      - REDIS_PASSWORD="heu-pwd"
    
resources:
  - deployment.yaml
  - service.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: app
    path: patch-service.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app
    path: patch-deployment.yaml