apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-test-app-v1
    version: v1
  name: app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  type: LoadBalancer
  selector:
    app: python-test-app-v1
    version: v1